### ISSUE TITLE
a ruby based version of kmer iterations and kmer graph preparation

### ISSUE THREAD

**Issue by sablokgaurav** [uio-bmi/kmercount#4]
def kmers(sequence, kmer)
=BEGIN
#!/usr/bin/ruby
#Universitat Potsdam
#Date: 2024-3-15
#Author: Gaurav Sablok
=END 
   seqsplitter = sequence.split(//)
   kmeriter = kmer.to_i
   seqkmers = []
  for i in 0..seqsplitter.length-kmeriter
     seqkmers.push(seqsplitter.slice(i,i-i+kmeriter).join)
  end
  return seqkmers.each { | iter | puts iter.to_s + "\t" + seqkmers.count(iter).to_s }
end

**Comment by torognes** [comment]
Sorry, but this does not seem relevant.

**Comment by sablokgaurav** [comment]
@torognes thats ok. I thought of completing it with a ruby version so that users if they are working with ruby can have both. If it doesnt seems like including the same in the same repository that makes sense and i already opened a new repository for the same. lets see if we can put something together. Have a nice week, Gaurav

**Comment by torognes** [comment]
Thanks. I think it would be better to make a ruby version in a separate repo. Best wishes

**Comment by sablokgaurav** [comment]
@torognes yes i already did it and you can find it here. May be we can link it together so that we can point the resources to each other. here is the link if you would like to host the same. I have already hosted yours. https://github.com/sablokgaurav/kmerstring-count-graph 

enjoy the evening, Gaurav
